openapi: 3.0.0
info:
  title: RentalX Documentation
  description: API for a rental service system.
  version: 1.0.0
  contact:
    email: viictor.alvess12@gmail.com

paths:
  /categories:
    post:
      tags:
        - Category
      summary: Create a category.
      description: Create a new category.
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/definitions/Category'
      responses:
        '201':
          description: Created
        '500':
          description: Category already exists
    get:
      tags:
        - Category
      summary: List categories.
      description: List all categories.
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/definitions/Categories'
        '500':
          description: Internal Server Error
  
  /categories/import:
    post:
      tags:
        - Category
      summary: Import categories.
      description: Create multiple categories.
      requestBody:
        content:
          'multipart/form-data':
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
            encoding:
              file:
                contentType: text/pdf
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error

  /specifications:
    post:
      tags:
        - Specification
      summary: Create a specification.
      description: Create a new specification.
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/definitions/Specification'
      responses:
        '201':
          description: Created
        '500':
          description: Specification already exists
    get:
      tags:
        - Specification
      summary: List specifications.
      description: List all specifications.
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/definitions/Specifications'
        '500':
          description: Internal Server Error

definitions:
  Category:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
    example:
      name: Category name sample
      description: Category description sample
  
  Categories:
    type: array
    items:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        created_at:
          type: string
          format: date-time
  
  Specification:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
    example:
      name: Specification name sample
      description: Specification description sample
  
  Specifications:
    type: array
    items:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        created_at:
          type: string
          format: date-time